spring.application.name=flight-service
server.port=8089

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/skywaysairlinedb
spring.datasource.username=root
spring.datasource.password=root@39

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION POOL (HIKARI)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.mphasis.skywaysairline.flightservice=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# ===============================
# JACKSON JSON
# ===============================
spring.jackson.default-property-inclusion=non_null

# ===============================
# SERVER ERROR SETTINGS
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never