spring.application.name=Notification-service
server.port=8084

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sourabhramteke1311@gmail.com
spring.mail.password=acyi budu tbth yozp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true