spring.application.name=booking-service
server.port=8090

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/skywaysairlinedb
spring.datasource.username=root
spring.datasource.password=root@39
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# MAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sourabhramteke1311@gmail.com
spring.mail.password=acyi budu tbth yozp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# RAZORPAY CONFIG
# ===============================
razorpay.key.id=rzp_test_SdKfg1SHSyvaok
razorpay.key.secret=0rzjsbOuiwOHVVpLfTlNzOyc

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.mphasis.skywaysairline.bookingservice=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# ===============================
# RESILIENCE4J - USER SERVICE
# ===============================
resilience4j.circuitbreaker.instances.userService.register-health-indicator=true
resilience4j.circuitbreaker.instances.userService.sliding-window-size=5
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.userService.automatic-transition-from-open-to-half-open-enabled=true

# ===============================
# RESILIENCE4J - FLIGHT SERVICE
# ===============================
resilience4j.circuitbreaker.instances.flightService.register-health-indicator=true
resilience4j.circuitbreaker.instances.flightService.sliding-window-size=5
resilience4j.circuitbreaker.instances.flightService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.flightService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.flightService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.flightService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.flightService.automatic-transition-from-open-to-half-open-enabled=true